# Generated by Django 4.1.2 on 2022-10-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='iEmployeeRecord',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='iYear',
            field=models.IntegerField(),
        ),
    ]
